# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-05-10 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20150209_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='email_to_verify',
            field=models.EmailField(max_length=254),
        ),
    ]
