# Generated by Django 2.2.3 on 2019-07-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190510_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='activate_user',
            field=models.BooleanField(default=True, help_text='If true, user.is_active will be set to true when verified.'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email_verified',
            field=models.BooleanField(default=False, help_text="Has this user's email been verified?"),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='preferred_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='profile_image',
            field=models.URLField(default='/static/accounts/marco_user.png', help_text="URL to the user's profile image."),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='real_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
